### PR TITLE
Add gh actions + rebuild readme

### PR DESCRIPTION
**Pull request by olivroy**

### CODE REVIEW

**Comment by olivroy** [comment]
@mdancho84 would you mind doing `usethis::use_pkgdown_github_pages()` for auto deployment?

**Comment by mdancho84** [comment]
Ok just let me know if anything changed. Nice work!

**Comment by olivroy** [comment]
@mdancho84 seems like it's still the old page showing up. Could you try to run `usethis::use_pkgdown_github_pages()` and do it locally ? or it may be doable in gh pages settings?

**Comment by mdancho84** [comment]
Let me do some things tonight. Have a workshop today. But after I can look into it.

**Pull request merged**
